### ISSUE TITLE
Port to Libadwaita 1.4

### ISSUE THREAD

**Issue by jamiethecat** [Vanilla-OS/apx-gui#21]
The widgets should be ported to Libadwaita 1.4, notably ToolbarView, for a quick overview see https://blogs.gnome.org/alicem/2023/09/15/libadwaita-1-4/

**Comment by MonsterObserver** [comment]
Currently working on a mockup for this, should be done semi-soon (hopefully).

**Comment by MonsterObserver** [comment]
![Screenshot from 2023-09-26 21-11-36](https://github.com/Vanilla-OS/apx-gui/assets/114881134/2a1a857f-7198-45b6-96f2-d7d6d65bf967)

Here's a rough idea of what it could look like.
