### ISSUE TITLE
Previously created containers are not detected

### ISSUE THREAD

**Issue by 00sapo** [Vanilla-OS/apx-gui#22]
Hello,
I installed `apx` in Manjaro using the AUR package. `apx` command works correctly and I tried both `--apt` and `--dnf`. I then compiled from the source and installed `apx-gui`. However, when running `apx-gui`, no container is detected. How can I add the existing ones?

**Comment by mirkobrombin** [comment]
Apx GUI is for Apx v2 while the `--dnf/--apt/..` flags are Apx v1. Please ask the maintainer to upgrade the package to Apx v2.
