### ISSUE TITLE
Publish To PyPI

### ISSUE THREAD

**Issue by Kaympe20** [Vanilla-OS/apx-gui#24]
Publishing to the Python Package Index will allow users to install apx-gui without having to self compile by using the distro-agnostic tool pip.

**Comment by coffandro** [comment]
Why would users want to do that though? the tools depends on apx being installed on the system which is only really possible on VanillaOS and Nix

**Comment by Kaympe20** [comment]
@coffandro @kbdharun  A lot of automatic packaging tools depend on a package being available on PyPI to create a distro package. It would be extremely beneficial for those looking to use APX on other distros.

**Comment by mirkobrombin** [comment]
That does not sound really a best practice to me. The apx GUI does not require many python dependencies if not zero at all, but it depends on some utilities like podman and apx itself. Not sure how PyPI would help here.
