### ISSUE TITLE
bug: subsystem creation succeeds but the error window is shown

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/apx-gui#30]
This issue still seems to be present even after the fix at https://github.com/Vanilla-OS/apx-gui/commit/3d460d3dd72dfb9045e8d9bacb2d06d0f9c6f576 (which is present in the latest dev image).

## Reference image

![Screenshot from 2024-01-17 10-55-27](https://github.com/Vanilla-OS/apx-gui/assets/26346867/2540a379-2f70-4b5b-be44-393b2ce59285)

**Comment by mirkobrombin** [comment]
Different bug, for some reason dbox is returning the wrong exit code on host, but the bug is not present on a container which spawns apx on the host via host-spawn. Quite funny.
