### ISSUE TITLE
When failed to create a subsystem, close button is not working

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Vanilla-OS/apx-gui#38]
![image](https://github.com/Vanilla-OS/apx/assets/58245644/1de03a93-3bab-4fb3-9f42-ce19e92458a1)

After clicking "Close", the dialog remain opened.

**Comment by mirkobrombin** [comment]
Please try launching the apx-gui issuing
```
host-shell
APX_VERBOSE=1 apx-gui
```

then provide the log once if fails to create the subsystem.

**Comment by wolf-yuan-6115** [comment]
> Please try launching the apx-gui issuing
> 
> ```
> host-shell
> APX_VERBOSE=1 apx-gui
> ```
> 
> then provide the log once if fails to create the subsystem.
> 
> After that, exit the host shell by issuing `exit`.

Hello, 

I tried to create a subsystem after it failed and it eventually succeeded. I created three subsystems and I cant reproduce it anymore.
