### ISSUE TITLE
Apx Gui fails to create container correctly

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/apx-gui#63]
When using apx's gui to create a container it fails when trying to start it up, and even fails in the cli
but when the cli creates it, both apx gui and the cli can access it

The error i get when trying to enter a container created by apx gui:
```
Error: OCI runtime error: crun: ptsname: Inappropriate ioctl for device
```

**Comment by mirkobrombin** [comment]
Can you try again after a reboot? I can't produce it.

**Comment by taukakao** [comment]
Actually, could you run "abroot upgrade" and after a reboot try again? 
I just tested with the latest version and can't reproduce this.

**Comment by fluoriteByte** [comment]
I have no updates available, so im currently running latest, and rebooting the system doesnt fix the issue

**Comment by taukakao** [comment]
@fluoriteByte 
When was the last upgrade?
You can check with "abroot status"

**Comment by fluoriteByte** [comment]
here are the details of the ABImage:
```
ABImage:
 • Digest: sha256:549b32cf38dee65481f13d641f0a370450abd12aba92e2c52513f0fa17edeeb6
 • Timestamp: 2024-07-19 14:42:59
 • Image: ghcr.io/vanilla-os/desktop:main
```

**Comment by kbdharun** [comment]
Hi, you seem to be using the image from 3 days ago, can you try running the command `abroot upgrade` once, if no updates are shown try `abroot upgrade --force` instead.

**Comment by fluoriteByte** [comment]
I force upgraded it, but it didnt download any layers + the checksum stayed the same:
```
ABImage:
 • Digest: sha256:549b32cf38dee65481f13d641f0a370450abd12aba92e2c52513f0fa17edeeb6
 • Timestamp: 2024-07-21 08:29:18
 • Image: ghcr.io/vanilla-os/desktop:main
```

But Apx-gui seems to have magically started working, idk what happened but it just did

**Comment by fluoriteByte** [comment]
Yeah i think  this has magically solved itself sooo im closing this issue until i get this bug again

**Comment by kbdharun** [comment]
Interesting, this is the first instance I have seen with SHA being the same while the timestamp is different, I have no idea how you got it.

**Comment by taukakao** [comment]
@kbdharun The timestamp is just the timestamp when you made the upgrade as far as  I know.
